Implement V2 Client
jwplayer/jwplatform-go pull request #12
Opened 2021-01-11 18:52 UTC by boyntoni

2021-01-11 18:59 UTC, waxidiotic requested changes

2021-01-11 18:59 UTC, waxidiotic commented on CHANGELOG.md
> +* Add client for JW Player V2 API's
```suggestion
* Add client for JW Player V2 APIs
```

2021-01-11 18:59 UTC, waxidiotic commented on api.go
> +// V2Client is a light wrapper around the http.defaultClient for interacting with JW Player V2 Platform API's
```suggestion
// V2Client is a light wrapper around the http.defaultClient for interacting with JW Player V2 Platform APIs
```

2021-01-12 18:41 UTC, ksindi commented on README.md
> +mySiteId := "9kzNUpe4"
Should do `siteId` for consistency

2021-01-12 19:38 UTC, waxidiotic approved these changes
Hi @ksindi !

2021-01-13 00:15 UTC, ksindi commented
Hi @waxidiotic!

2021-01-13 22:05 UTC, ksindi commented on README.md
> +The V1 Client remains available for use, but is deprecated. We strongly recommend using the V2 Client. For documentation on the V1 client, please refer to the `v1` submodule.
Minor Inconsistency "V1 Client" vs. "V1 client"

2021-01-13 22:27 UTC, emptyflash approved these changes

2021-01-14 16:18 UTC, boyntoni commented on api.go
> +func (c *V2Client) Request(method, path string, response interface{}, data interface{}, queryParams *QueryParams) error {
@emptyflash Just wanted to run the new solution by you, found a nice library for this

2021-01-14 19:52 UTC, emptyflash approved these changes
Nice, I like this query string library

2021-01-14 20:20 UTC, merged